apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pngjhic2t-nodejs
  janus-idp.io/tekton: pngjhic2t-nodejs
  backstage.io/kubernetes-id: pngjhic2t-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pngjhic2t-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
